---
title: "Labs"
---

These mini projects will have you explore statistical topics using R. You can use the `startLab` function in the `DATA606` package to get started, or copy the templates from the links below. **Please submit a PDF (preferred) or HTML file along with your Rmarkdown file.** Be sure to answer all questions in lab, not just the *on your own section.* Labs should be submitted on Blackboard.

Here are the commands you can use to start the labs (note change `Lab1` to the appropriate lab number).

```{r, eval=FALSE}
library(DATA606)
getLabs() # This will list all the labs available
startLab('Lab1') # This will copy the lab folder to your working directory
```

<ol start='1'>
<li value='1'> <a href='https://htmlpreview.github.io/?https://github.com/jbryer/DATA606/blob/master/inst/labs/Lab1/Lab1_intro_to_r.html'>Introduction to R and RStudio</a> </li>

<li value='2'> <a href='https://htmlpreview.github.io/?https://github.com/jbryer/DATA606/blob/master/inst/labs/Lab2/Lab2_intro_to_data.html'>Introduction to Data</a> </li>

<li value='3'> <a href='https://htmlpreview.github.io/?https://github.com/jbryer/DATA606/blob/master/inst/labs/Lab3/Lab3_probability.html'>Probability</a> </li>

<li value='4'> <a href='https://htmlpreview.github.io/?https://github.com/jbryer/DATA606/blob/master/inst/labs/Lab4/Lab4_normal_distribution.html'>Distributions of Random Variables</a></li>

<li value='5'> Foundations for Statistical Inference 
<ol type="A">
<li value='A'> <a href='https://htmlpreview.github.io/?https://github.com/jbryer/DATA606/blob/master/inst/labs/Lab5a/Lab5a_sampling_distributions.html'>Sampling Distributions</a> </li>
<li value='B'> <a href='https://htmlpreview.github.io/?https://github.com/jbryer/DATA606/blob/master/inst/labs/Lab5b/Lab5b_confidence_intervals.html'>Confidence Levels</a> </li>
</ol></li>

<li value='6'> <a href='https://htmlpreview.github.io/?https://github.com/jbryer/DATA606/blob/master/inst/labs/Lab6/Lab6_inf_for_categorical_data.html'>Inference for Categorical Data</a> </li>

<li value='7'> <a href='https://htmlpreview.github.io/?https://github.com/jbryer/DATA606/blob/master/inst/labs/Lab7/Lab7_inf_for_numerical_data.html'>Inference for Numerical Data</a> </li>

<li value='8'> <a href='https://htmlpreview.github.io/?https://github.com/jbryer/DATA606/blob/master/inst/labs/Lab8/Lab8_simple_regression.html'>Introduction to Linear Regression</a> </li>

<li value='9'> <a href='https://htmlpreview.github.io/?https://github.com/jbryer/DATA606/blob/master/inst/labs/Lab9/Lab9_multiple_regression.html'>Multiple Linear Regerssion</a> </li>
</ol>

